{
  imports = [
    ./whichkey.nix
    ./nvim-autopairs.nix
    ./mini.nix
    ./oil.nix
    ./ufo.nix
    ./flash.nix
    ./comment.nix
    ./copilot.nix
    ./grapple.nix
    ./harpoon.nix
    ./hardtime.nix
    ./undotree.nix
    ./illuminate.nix
    ./yaml-companion.nix
    ./netman.nix
  ];
}
